language: python

python:
  - "2.7"

install:
  - pip install -r requirements_dev.txt
  - pip install coveralls

before_script:
  - python testserver.py >testserver.log 2>&1 &
  - sleep 3 # allow testserver to start

script: make test-coverage

after_failure: cat testserver.log

after_success: coveralls
